services:
  - type: web
    name: QuanlyBanSach
    runtime: ruby
    plan: free
    buildCommand: >
      bundle install &&
      bundle exec rake db:migrate &&
      bundle exec rake db:seed &&
      bundle exec rake assets:clean &&
      bundle exec rake assets:precompile
    startCommand: 'bin/rails server'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: quanlybansach_0hzu
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2

databases:
  - name: quanlybansach_0hzu
    plan: free
